### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by Roywangj** [CVMI-Lab/FS3D#1]
Hi,

This is an interesting work, and when will this code be released?

**Comment by Shizhen-ZHAO** [comment]
Hi, thanks for your interest in our work. 
The code will be released in this weekend. I will let you know when the code comes.

**Comment by Roywangj** [comment]
Hi, thanks for your patient reply.  It's a good news.

**Comment by Shizhen-ZHAO** [comment]
Sorry, I still have some bugs to work out. I will fix them as soon as possible.  
Sorry again.

**Comment by Roywangj** [comment]
That's ok, thanks for your reply.


Shizhen Zhao ***@***.***> 于2022年11月20日周日 18:34写道：
