### ISSUE TITLE
Multi-gpu train/test

### ISSUE THREAD

**Issue by fukancv** [CVMI-Lab/FS3D#2]
Hi, can the network be trained/tested through multiple gpus? How long does it take to train by using a gpu (e.g., 3090)? Moreover, I have requested the datasets via email, but I haven't received a response. Thanks.

**Comment by Shizhen-ZHAO** [comment]
Hi, thanks for your interest. Sorry for the late reply, I just found your email in spam folder. 
I only use one GPU (i.e. 3090) for experiments and didn’t try multi-GPU training. The training time is less than 7 hours.
I have responded to you about the dataset link via email. If you have any questions, you can email me directly. 
Thanks again.

**Comment by monkeyrom** [comment]
I also requested the datasets via email, just to tell you in case it's in the spam folder. Thank you in advance.

**Comment by Lujun-Zhang** [comment]
I also sent an email requesting a dataset on April 18, 2022, but did not receive a response

**Comment by Shizhen-ZHAO** [comment]
Hi Lujun. 

Thanks for your interest. I just found your email in my spam folder. I have replied the email. Please check it again.
