### ISSUE TITLE
'sunrgbd_infos_train_v0_fs_plus.pkl'

### ISSUE THREAD

**Issue by STLIFE97** [CVMI-Lab/FS3D#7]
How to generate a 'sunrgbd_infos_train_v0_fs_plus.pkl' file, I want to use other dataset, I want to refer to the generation and writing of your pkl file.

**Comment by Shizhen-ZHAO** [comment]
Hi, you could leave your email here first. I'll send you the code files after refactoring them. Thanks.

**Comment by STLIFE97** [comment]
575888625@qq.com
Thanks!
